### ISSUE TITLE
1.0.0 release?

### ISSUE THREAD

**Issue by phated** [hughsk/clone-stats#1]
Vinyl uses this to clone stats and it has been downloaded a ton without any issues.  Mind bumping to 1.0 proper?

**Comment by hughsk** [comment]
Sure thing! On it :)

**Comment by hughsk** [comment]
Oops, forgot to close the issue — done!

**Comment by phated** [comment]
Many thanks.  I'm trying to get all the gulp deps bumped to >=1.0
